FROM almalinux:9

RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled crb
RUN dnf install -y \
  rsyslog \
  systemd \
  systemd-pam \
  sudo \
  dbus \
  nano less man-db \
  iproute iputils \
  hwloc \
  json-c \
  pmix \
  numactl

RUN dnf install -y epel-release
RUN dnf install -y munge

RUN sed -i 's/^\($ModLoad imklog\)/#\1/' /etc/rsyslog.conf

RUN rm -f /lib/systemd/system/systemd*udev* \
  && rm -f /lib/systemd/system/getty.target

RUN ln -s /lib/systemd/system/dbus.service \
      /lib/systemd/system/multi-user.target.wants/dbus.service

#RUN ln -s /lib/systemd/system/systemd-logind.service \
#      /lib/systemd/system/multi-user.target.wants/systemd-logind.service

RUN useradd --home /tmp --shell /bin/bash slurm

CMD [ "/sbin/init" ]
