name: Build all Docker images

on:
  workflow_dispatch:
  push:
    branches-ignore: [test*, "main", "dev"]
    tags:
      - 'v*.*.*'
  release:
    types: [created]
  schedule:
    # Weekly build every Wednesday at 3 AM UTC
    - cron: '0 3 * * 3'

env:
  REGISTRY: ghcr.io
  IMAGE_REPO_OWNER: papamoose

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          # Define all OS variants here in one place
          - variant: almalinux9
            dockerfile: almalinux.9
            image_name: container-systemd-almalinux-9
            labels:
              title: almalinux-9
              description: Almalinux 9 container running systemd
          - variant: ubi8
            dockerfile: ubi.8
            image_name: container-systemd-ubi8
            labels:
              title: ubi8
              description: UBI 8 container running systemd
          - variant: ubi9
            dockerfile: ubi.9
            image_name: container-systemd-ubi9
            labels:
              title: ubi9
              description: UBI 9 container running systemd
          - variant: ubuntu2204
            dockerfile: ubuntu.2204
            image_name: container-systemd-ubuntu-2204
            labels:
              title: ubuntu-2204
              description: Ubuntu 22.04 container running systemd
          - variant: ubuntu2404
            dockerfile: ubuntu.2404
            image_name: container-systemd-ubuntu-2404
            labels:
              title: ubuntu-2404
              description: Ubuntu 24.04 container running systemd

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup QEMU and Buildx once per job (not per matrix variant)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Login only happens once for all variants in the job
      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Use metadata action to generate tags dynamically
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO_OWNER }}/${{ matrix.image_name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,${{ github.event.release.tag_name }}
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}

      - name: Build and push image
        id: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPO_OWNER }}/${{ matrix.image_name }}:${{ steps.meta.outputs.tags }}
          labels: $|
            maintainer=papamoose
            org.opencontainers.image.title=${{ matrix.labels.title }}
            org.opencontainers.image.description=${{ matrix.labels.description }}
            org.opencontainers.image.vendor=Papamoose Co

      # Only push on non-pull-requests (applies to all variants)
      - name: Determine if should push
        run: echo ::set-output name=should_push::${{ !contains(github.event_name, 'pull_request') }}
        id: set-push

      # Conditional push using the above output
      - name: Actual Build and Push (conditional)
        uses: docker/build-push-action@v4
        if: ${{ steps.set-push.outputs.should_push == 'true' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
